services:
  mongo:
    image: mongo:6.0
    container_name: local_cosmos_mongo_emulator
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: hilton_reservations
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    build:
      context: auth-service
      dockerfile: Dockerfile
    container_name: hilton_auth_service
    restart: unless-stopped
    environment:
      COSMOS_MONGO_URI: mongodb://mongo:27017/hilton_reservations
      PORT: 5000
      JWT_SECRET: dd9eddf2-01a3-468b-8f3e-18f427d898c5
      JWT_EXPIRES_IN: 3600s
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  reservation-service:
    build:
      context: reservation-service
      dockerfile: Dockerfile
    container_name: hilton_reservation_service
    restart: unless-stopped
    environment:
      # Override .env for Docker networking
      COSMOS_MONGO_URI: mongodb://mongo:27017/hilton_reservations
      PORT: 4000
      JWT_SECRET: dd9eddf2-01a3-468b-8f3e-18f427d898c5
      JWT_EXPIRES_IN: 3600s
      GRAPHQL_PLAYGROUND: "true"
      AUTH_INTROSPECTION_URL: http://auth-service:5000/auth/introspect
      INTROSPECTION_CACHE_TTL_MS: 60000
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - auth-service

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: hilton_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - reservation-service
      - auth-service

volumes:
  mongo_data:
